version: '3.7'
services:
  ##### INFLUXDB
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
      # Mount for influxdb data directory and configuration
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  ##### TELEGRAF
  telegraf:
    image: telegraf
    container_name: telegraf
    ports:
      - 8186:8186
    links:
      - "influxdb"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  ##### CHRONOGRAF
  chronograf:
    image: chronograf
    container_name: chronograf
    ports:
      - 8888:8888
    command: [ "chronograf", "--influxdb-url=http://influxdb:8086" ]
    links:
      - "influxdb:influxdb"

  ##### GRAFANA
  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - "influxdb:influxdb"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
    volumes:
      - ./data/grafana/grafana:/var/lib/grafana
    # restart: always

  ##### NODE-RED
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    volumes:
      - './node_red_data:/data'
    ports:
      - 1880:1880